#!/bin/sh
# このシェルスクリプトをpathの通っている場所に配置すること（例: .local/bin）

DOCKER_IMAGE="mynvim"

DOCKER_OPTIONS=(
  "-e" "HOME=$HOME"
)
DOCKER_OPTIONS+=(
  "-v" "$HOME:$HOME:cached"
  "-v" "/var/www:/var/www"
  "-v" "/var/tmp:/var/tmp"
  "-v" "$HOME/Desktop/dev/development-environments/neovim/nvim:$HOME/.config/nvim"
  "--name" $DOCKER_IMAGE
)
echo $DOCKER_OPTIONS

docker run --rm -it -u $(id -u):$(id -g) "${DOCKER_OPTIONS[@]}" --workdir=$(pwd) "${DOCKER_IMAGE}" "$@"
